### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by God-Zalo** [God-Zalo/Kanterita-3#4]
Macro roadmap for kanterita3 should be something like this:

- [x] Deploy webserver
- [x] Deploy db
- [x] Upload csv file
- [ ] Parse and validate data
- [x] POST validated data to db

Milestones do not require to be addressed in this specific order
